---
- name: Configure Magento 2 Environment
  hosts: all
  become: yes
  vars:
    magento_domain: "test.mgt.com"
    phpmyadmin_domain: "pma.mgt.com"
    magento_user: "test-ssh"
    magento_group: "clp"
    magento_db_password: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=16') }}"
    magento_admin_password: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=16') }}"
    mariadb_root_password: "{{ lookup('file', '/root/magento_credentials/mariadb_root_password.txt') | regex_replace('^MariaDB Root Password: (.*)$', '\\1') }}"
    magento_admin_password: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=16') }}"

  roles:
    - role: common
    - role: php
    - role: mysql
    - role: nginx
    - role: elasticsearch
    - role: redis
    - role: magento2
    - role: phpmyadmin
    - role: varnish
  handlers:
    - include: roles/handlers/main.yml
