- name: Install NGINX
  apt:
    name: nginx
    state: present

- name: Configure NGINX to run as test-ssh user
  lineinfile:
    path: /etc/nginx/nginx.conf
    regexp: '^user'
    line: 'user test-ssh;'
