- name: Ensure test-ssh user exists
  user:
    name: test-ssh
    state: present
    system: yes

- name: Ensure clp group exists
  group:
    name: clp
    state: present

- name: Add test-ssh user to www-data group
  user:
    name: test-ssh
    groups: clp
    append: yes
    
- name: Install NGINX
  apt:
    name: nginx
    state: present

- name: Configure NGINX to run as test-ssh user
  lineinfile:
    path: /etc/nginx/nginx.conf
    regexp: '^user'
    line: 'user test-ssh clp;'
  notify: Reload NGINX

- name: Copy Magento NGINX configuration
  template:
    src: magento_nginx.conf.j2
    dest: /etc/nginx/sites-available/magento.conf
  notify: Test NGINX configuration

- name: Enable Magento NGINX configuration
  file:
    src: /etc/nginx/sites-available/magento.conf
    dest: /etc/nginx/sites-enabled/magento.conf
    state: link
  notify: Test NGINX configuration

- name: Remove default NGINX configuration
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Test NGINX configuration
