- name: Ensure test-ssh user exists
  user:
    name: test-ssh
    state: present
    system: yes
    
- name: Install NGINX
  apt:
    name: nginx
    state: present

- name: Configure NGINX to run as test-ssh user
  lineinfile:
    path: /etc/nginx/nginx.conf
    regexp: '^user'
    line: 'user test-ssh;'
  notify: Reload NGINX

- name: Ensure www-data group exists
  group:
    name: www-data
    state: present

- name: Add test-ssh user to www-data group
  user:
    name: test-ssh
    groups: www-data
    append: yes
