- name: Install Varnish
  apt:
    name: varnish
    state: present

- name: Configure Varnish for Magento
  template:
    src: default.vcl.j2
    dest: /etc/varnish/default.vcl
  notify: Restart Varnish
